"""Add constraints and partial index for worker fixes

Revision ID: 44cb8bcea472
Revises: 9e8c6e061164
Create Date: 2026-08-17 16:32:19.904578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cb8bcea472'
down_revision: Union[str, Sequence[str], None] = '9e8c6e061164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data Repair: Backfill replication_health
    op.execute("UPDATE projects SET replication_health = 'UNKNOWN' WHERE replication_health IS NULL")
    
    # Data Repair: Handle NULLs in sync_jobs before setting NOT NULL constraints
    op.execute("DELETE FROM sync_jobs WHERE project_id IS NULL")
    op.execute("UPDATE sync_jobs SET status = 'FAILED' WHERE status IS NULL")
    op.execute("UPDATE sync_jobs SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # Data Repair: Resolve duplicate active jobs per project
    op.execute("""
        UPDATE sync_jobs
        SET status = 'FAILED', error_message = 'Marked as failed during migration duplicate cleanup'
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY project_id ORDER BY created_at DESC) as rn
                FROM sync_jobs
                WHERE status NOT IN ('SUCCESS', 'FAILED')
            ) t WHERE t.rn > 1
        )
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.alter_column('project_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=False)
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.create_index('ix_sync_jobs_active', ['project_id'], unique=True, postgresql_where=sa.text("status NOT IN ('SUCCESS', 'FAILED')"), sqlite_where=sa.text("status NOT IN ('SUCCESS', 'FAILED')"))
        batch_op.create_index('ix_sync_jobs_claim', ['status', 'lease_expires_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_jobs_claim')
        batch_op.drop_index('ix_sync_jobs_active', postgresql_where=sa.text("status NOT IN ('SUCCESS', 'FAILED')"), sqlite_where=sa.text("status NOT IN ('SUCCESS', 'FAILED')"))
        batch_op.alter_column('created_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch_op.alter_column('project_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###
