"""Add sync_jobs and replication_health

Revision ID: 9e8c6e061164
Revises: e0d48b29416c
Create Date: 2026-08-17 16:13:30.895254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8c6e061164'
down_revision: Union[str, Sequence[str], None] = 'e0d48b29416c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_jobs_project_id'), 'sync_jobs', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('replication_health', sa.String(length=50), nullable=True))
    op.drop_column('projects', 'sync_locked_at')
    op.drop_column('projects', 'sync_status')
    op.drop_column('projects', 'sync_error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sync_error', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('projects', sa.Column('sync_status', sa.VARCHAR(length=50), server_default=sa.text("'IDLE'"), nullable=True))
    op.add_column('projects', sa.Column('sync_locked_at', sa.DATETIME(), nullable=True))
    op.drop_column('projects', 'replication_health')
    op.drop_index(op.f('ix_sync_jobs_project_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
