"""Add sync state machine columns

Revision ID: e0d48b29416c
Revises: 21eb44fa2640
Create Date: 2026-08-17 15:46:49.022687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d48b29416c'
down_revision: Union[str, Sequence[str], None] = '21eb44fa2640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sync_status', sa.String(length=50), server_default='IDLE', nullable=True))
    op.add_column('projects', sa.Column('sync_error', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('sync_locked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sync_locked_at')
    op.drop_column('projects', 'sync_error')
    op.drop_column('projects', 'sync_status')
    # ### end Alembic commands ###
